=== johnbhurst/dbunit/src/dtd/flatXmlTableTest.dtd
<!ELEMENT dataset (
    TEST_TABLE*,
    MISSING_VALUES*)>

<!ELEMENT TEST_TABLE EMPTY>
<!ATTLIST TEST_TABLE
    COLUMN0 CDATA #REQUIRED
    COLUMN1 CDATA #REQUIRED
    COLUMN2 CDATA #REQUIRED
    COLUMN3 CDATA #REQUIRED
>

<!ELEMENT MISSING_VALUES EMPTY>
<!ATTLIST MISSING_VALUES
    COLUMN0 CDATA #IMPLIED
    COLUMN1 CDATA #IMPLIED
    COLUMN2 CDATA #IMPLIED
>

=== johnbhurst/dbunit/dbunit/src/xml/sortedTableTest.xml
<!DOCTYPE dataset    SYSTEM     "../dtd/flatXmlTableTest.dtd">
<dataset>
	<TEST_TABLE COLUMN0="row 4 col 0" COLUMN1="row 4 col 1" COLUMN2="row 4 col 2" COLUMN3="row 4 col 3"/>
	<TEST_TABLE COLUMN0="row 0 col 0" COLUMN1="row 0 col 1" COLUMN2="row 0 col 2" COLUMN3="row 0 col 3"/>
	<TEST_TABLE COLUMN0="row 2 col 0" COLUMN1="row 2 col 1" COLUMN2="row 2 col 2" COLUMN3="row 2 col 3"/>
	<TEST_TABLE COLUMN0="row 1 col 0" COLUMN1="row 1 col 1" COLUMN2="row 1 col 2" COLUMN3="row 1 col 3"/>
	<TEST_TABLE COLUMN0="row 5 col 0" COLUMN1="row 5 col 1" COLUMN2="row 5 col 2" COLUMN3="row 5 col 3"/>
	<TEST_TABLE COLUMN0="row 3 col 0" COLUMN1="row 3 col 1" COLUMN2="row 3 col 2" COLUMN3="row 3 col 3"/>
	<MISSING_VALUES COLUMN0="0"/>
	<MISSING_VALUES COLUMN0="0" COLUMN2="1"/>
	<MISSING_VALUES COLUMN0="0"/>	
	<MISSING_VALUES COLUMN0="0" COLUMN2="0"/>
	<MISSING_VALUES COLUMN0="0"/>	
	
</dataset>
