=== johnbhurst/dbunit/dbunit/src/dtd/flatDtdProducerTest.dtd
<!ELEMENT dataset (
    DUPLICATE_TABLE*,
    SECOND_TABLE*,
    TEST_TABLE*,
    NOT_NULL_TABLE*,
    EMPTY_TABLE*)>

<!ELEMENT TEST_TABLE EMPTY>
<!ATTLIST TEST_TABLE
    COLUMN0 CDATA #IMPLIED
    COLUMN1 CDATA #IMPLIED
    COLUMN2 CDATA #IMPLIED
    COLUMN3 CDATA #IMPLIED
>

<!ELEMENT SECOND_TABLE EMPTY>
<!ATTLIST SECOND_TABLE
    COLUMN0 CDATA #IMPLIED
    COLUMN1 CDATA #IMPLIED
    COLUMN2 CDATA #IMPLIED
    COLUMN3 CDATA #IMPLIED
>

<!ELEMENT DUPLICATE_TABLE EMPTY>
<!ATTLIST DUPLICATE_TABLE
    COLUMN0 CDATA #IMPLIED
    COLUMN1 CDATA #IMPLIED
    COLUMN2 CDATA #IMPLIED
    COLUMN3 CDATA #IMPLIED
>

<!ELEMENT NOT_NULL_TABLE EMPTY>
<!ATTLIST NOT_NULL_TABLE
    COLUMN0 CDATA #REQUIRED
    COLUMN1 CDATA #REQUIRED
    COLUMN2 CDATA #REQUIRED
    COLUMN3 CDATA #REQUIRED
>

<!ELEMENT EMPTY_TABLE EMPTY>
<!ATTLIST EMPTY_TABLE
    COLUMN0 CDATA #IMPLIED
    COLUMN1 CDATA #IMPLIED
    COLUMN2 CDATA #IMPLIED
    COLUMN3 CDATA #IMPLIED
>

=== johnbhurst/dbunit/dbunit/src/xml/flatXmlProducerTest.xml
<!DOCTYPE dataset SYSTEM "../dtd/flatDtdProducerTest.dtd">
<dataset>
	<DUPLICATE_TABLE COLUMN0="row 0 col 0" COLUMN1="row 0 col 1" COLUMN2="row 0 col 2" COLUMN3="row 0 col 3"/>
	<SECOND_TABLE COLUMN0="row 0 col 0" COLUMN1="row 0 col 1" COLUMN2="row 0 col 2" COLUMN3="row 0 col 3"/>
	<SECOND_TABLE COLUMN0="row 1 col 0" COLUMN1="row 1 col 1" COLUMN2="row 1 col 2" COLUMN3="row 1 col 3"/>
	<TEST_TABLE COLUMN0="row 0 col 0" COLUMN1="row 0 col 1" COLUMN2="row 0 col 2" COLUMN3="row 0 col 3"/>
	<TEST_TABLE COLUMN0="row 1 col 0" COLUMN1="row 1 col 1" COLUMN2="row 1 col 2" COLUMN3="row 1 col 3"/>
	<TEST_TABLE COLUMN0="row 2 col 0" COLUMN1="row 2 col 1" COLUMN2="row 2 col 2" COLUMN3="row 2 col 3"/>
	<NOT_NULL_TABLE COLUMN0="row 0 col 0" COLUMN1="row 0 col 1" COLUMN2="row 0 col 2" COLUMN3="row 0 col 3"/>
	<EMPTY_TABLE/>
</dataset>
